// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Entity1ServiceClient is the client API for Entity1Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Entity1ServiceClient interface {
	CreateEntity1(ctx context.Context, in *CreateEntity1Request, opts ...grpc.CallOption) (*CreateEntity1Response, error)
	UpdateEntity1(ctx context.Context, in *UpdateEntity1Request, opts ...grpc.CallOption) (*UpdateEntity1Response, error)
	GetEntity1Details(ctx context.Context, in *GetEntity1DetailsRequest, opts ...grpc.CallOption) (*GetEntity1DetailsResponse, error)
	DeleteEntity1(ctx context.Context, in *DeleteEntity1Request, opts ...grpc.CallOption) (*DeleteEntity1Response, error)
}

type entity1ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEntity1ServiceClient(cc grpc.ClientConnInterface) Entity1ServiceClient {
	return &entity1ServiceClient{cc}
}

func (c *entity1ServiceClient) CreateEntity1(ctx context.Context, in *CreateEntity1Request, opts ...grpc.CallOption) (*CreateEntity1Response, error) {
	out := new(CreateEntity1Response)
	err := c.cc.Invoke(ctx, "/api.proto.v1.Entity1Service/CreateEntity1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entity1ServiceClient) UpdateEntity1(ctx context.Context, in *UpdateEntity1Request, opts ...grpc.CallOption) (*UpdateEntity1Response, error) {
	out := new(UpdateEntity1Response)
	err := c.cc.Invoke(ctx, "/api.proto.v1.Entity1Service/UpdateEntity1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entity1ServiceClient) GetEntity1Details(ctx context.Context, in *GetEntity1DetailsRequest, opts ...grpc.CallOption) (*GetEntity1DetailsResponse, error) {
	out := new(GetEntity1DetailsResponse)
	err := c.cc.Invoke(ctx, "/api.proto.v1.Entity1Service/GetEntity1Details", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entity1ServiceClient) DeleteEntity1(ctx context.Context, in *DeleteEntity1Request, opts ...grpc.CallOption) (*DeleteEntity1Response, error) {
	out := new(DeleteEntity1Response)
	err := c.cc.Invoke(ctx, "/api.proto.v1.Entity1Service/DeleteEntity1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Entity1ServiceServer is the server API for Entity1Service service.
// All implementations must embed UnimplementedEntity1ServiceServer
// for forward compatibility
type Entity1ServiceServer interface {
	CreateEntity1(context.Context, *CreateEntity1Request) (*CreateEntity1Response, error)
	UpdateEntity1(context.Context, *UpdateEntity1Request) (*UpdateEntity1Response, error)
	GetEntity1Details(context.Context, *GetEntity1DetailsRequest) (*GetEntity1DetailsResponse, error)
	DeleteEntity1(context.Context, *DeleteEntity1Request) (*DeleteEntity1Response, error)
	mustEmbedUnimplementedEntity1ServiceServer()
}

// UnimplementedEntity1ServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEntity1ServiceServer struct {
}

func (UnimplementedEntity1ServiceServer) CreateEntity1(context.Context, *CreateEntity1Request) (*CreateEntity1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEntity1 not implemented")
}
func (UnimplementedEntity1ServiceServer) UpdateEntity1(context.Context, *UpdateEntity1Request) (*UpdateEntity1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEntity1 not implemented")
}
func (UnimplementedEntity1ServiceServer) GetEntity1Details(context.Context, *GetEntity1DetailsRequest) (*GetEntity1DetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntity1Details not implemented")
}
func (UnimplementedEntity1ServiceServer) DeleteEntity1(context.Context, *DeleteEntity1Request) (*DeleteEntity1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEntity1 not implemented")
}
func (UnimplementedEntity1ServiceServer) mustEmbedUnimplementedEntity1ServiceServer() {}

// UnsafeEntity1ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Entity1ServiceServer will
// result in compilation errors.
type UnsafeEntity1ServiceServer interface {
	mustEmbedUnimplementedEntity1ServiceServer()
}

func RegisterEntity1ServiceServer(s grpc.ServiceRegistrar, srv Entity1ServiceServer) {
	s.RegisterService(&Entity1Service_ServiceDesc, srv)
}

func _Entity1Service_CreateEntity1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntity1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Entity1ServiceServer).CreateEntity1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.v1.Entity1Service/CreateEntity1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Entity1ServiceServer).CreateEntity1(ctx, req.(*CreateEntity1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Entity1Service_UpdateEntity1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEntity1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Entity1ServiceServer).UpdateEntity1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.v1.Entity1Service/UpdateEntity1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Entity1ServiceServer).UpdateEntity1(ctx, req.(*UpdateEntity1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Entity1Service_GetEntity1Details_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntity1DetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Entity1ServiceServer).GetEntity1Details(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.v1.Entity1Service/GetEntity1Details",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Entity1ServiceServer).GetEntity1Details(ctx, req.(*GetEntity1DetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Entity1Service_DeleteEntity1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEntity1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Entity1ServiceServer).DeleteEntity1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.v1.Entity1Service/DeleteEntity1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Entity1ServiceServer).DeleteEntity1(ctx, req.(*DeleteEntity1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Entity1Service_ServiceDesc is the grpc.ServiceDesc for Entity1Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Entity1Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.v1.Entity1Service",
	HandlerType: (*Entity1ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntity1",
			Handler:    _Entity1Service_CreateEntity1_Handler,
		},
		{
			MethodName: "UpdateEntity1",
			Handler:    _Entity1Service_UpdateEntity1_Handler,
		},
		{
			MethodName: "GetEntity1Details",
			Handler:    _Entity1Service_GetEntity1Details_Handler,
		},
		{
			MethodName: "DeleteEntity1",
			Handler:    _Entity1Service_DeleteEntity1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/entity1.proto",
}
