// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: docs/proto/v1/entity1.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEntity1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 bool   `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2 int64  `protobuf:"varint,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3 string `protobuf:"bytes,3,opt,name=field3,proto3" json:"field3,omitempty"`
}

func (x *CreateEntity1Request) Reset() {
	*x = CreateEntity1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_v1_entity1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEntity1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntity1Request) ProtoMessage() {}

func (x *CreateEntity1Request) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_entity1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntity1Request.ProtoReflect.Descriptor instead.
func (*CreateEntity1Request) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_entity1_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEntity1Request) GetField1() bool {
	if x != nil {
		return x.Field1
	}
	return false
}

func (x *CreateEntity1Request) GetField2() int64 {
	if x != nil {
		return x.Field2
	}
	return 0
}

func (x *CreateEntity1Request) GetField3() string {
	if x != nil {
		return x.Field3
	}
	return ""
}

type CreateEntity1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateEntity1Response) Reset() {
	*x = CreateEntity1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_v1_entity1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEntity1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntity1Response) ProtoMessage() {}

func (x *CreateEntity1Response) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_entity1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntity1Response.ProtoReflect.Descriptor instead.
func (*CreateEntity1Response) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_entity1_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEntity1Response) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateEntity1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Field3 string `protobuf:"bytes,2,opt,name=field3,proto3" json:"field3,omitempty"`
}

func (x *UpdateEntity1Request) Reset() {
	*x = UpdateEntity1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_v1_entity1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEntity1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntity1Request) ProtoMessage() {}

func (x *UpdateEntity1Request) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_entity1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntity1Request.ProtoReflect.Descriptor instead.
func (*UpdateEntity1Request) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_entity1_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateEntity1Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEntity1Request) GetField3() string {
	if x != nil {
		return x.Field3
	}
	return ""
}

type UpdateEntity1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateEntity1Response) Reset() {
	*x = UpdateEntity1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_v1_entity1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEntity1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntity1Response) ProtoMessage() {}

func (x *UpdateEntity1Response) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_entity1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntity1Response.ProtoReflect.Descriptor instead.
func (*UpdateEntity1Response) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_entity1_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEntity1Response) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetEntity1DetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetEntity1DetailsRequest) Reset() {
	*x = GetEntity1DetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_v1_entity1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEntity1DetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntity1DetailsRequest) ProtoMessage() {}

func (x *GetEntity1DetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_entity1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntity1DetailsRequest.ProtoReflect.Descriptor instead.
func (*GetEntity1DetailsRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_entity1_proto_rawDescGZIP(), []int{4}
}

func (x *GetEntity1DetailsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEntity1DetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Field1 bool   `protobuf:"varint,2,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2 int64  `protobuf:"varint,3,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3 string `protobuf:"bytes,4,opt,name=field3,proto3" json:"field3,omitempty"`
}

func (x *GetEntity1DetailsResponse) Reset() {
	*x = GetEntity1DetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_v1_entity1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEntity1DetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntity1DetailsResponse) ProtoMessage() {}

func (x *GetEntity1DetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_entity1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntity1DetailsResponse.ProtoReflect.Descriptor instead.
func (*GetEntity1DetailsResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_entity1_proto_rawDescGZIP(), []int{5}
}

func (x *GetEntity1DetailsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEntity1DetailsResponse) GetField1() bool {
	if x != nil {
		return x.Field1
	}
	return false
}

func (x *GetEntity1DetailsResponse) GetField2() int64 {
	if x != nil {
		return x.Field2
	}
	return 0
}

func (x *GetEntity1DetailsResponse) GetField3() string {
	if x != nil {
		return x.Field3
	}
	return ""
}

type DeleteEntity1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteEntity1Request) Reset() {
	*x = DeleteEntity1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_v1_entity1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEntity1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntity1Request) ProtoMessage() {}

func (x *DeleteEntity1Request) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_entity1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntity1Request.ProtoReflect.Descriptor instead.
func (*DeleteEntity1Request) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_entity1_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEntity1Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteEntity1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteEntity1Response) Reset() {
	*x = DeleteEntity1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_v1_entity1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEntity1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntity1Response) ProtoMessage() {}

func (x *DeleteEntity1Response) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_entity1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntity1Response.ProtoReflect.Descriptor instead.
func (*DeleteEntity1Response) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_entity1_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEntity1Response) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_docs_proto_v1_entity1_proto protoreflect.FileDescriptor

var file_docs_proto_v1_entity1_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x64, 0x6f, 0x63, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x22, 0x5e, 0x0a, 0x14, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x22, 0x27, 0x0a, 0x15, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x33, 0x22, 0x2f, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x31, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x73, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f,
	0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32,
	0x84, 0x03, 0x0a, 0x0e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x58, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x31, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0d,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31, 0x12, 0x22, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x31, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x26, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x31, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31, 0x12, 0x22, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x31, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x75, 0x6c, 0x6c, 0x4e, 0x69, 0x6c, 0x2f, 0x67, 0x6f, 0x2d,
	0x63, 0x6c, 0x65, 0x61, 0x6e, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_docs_proto_v1_entity1_proto_rawDescOnce sync.Once
	file_docs_proto_v1_entity1_proto_rawDescData = file_docs_proto_v1_entity1_proto_rawDesc
)

func file_docs_proto_v1_entity1_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_entity1_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_entity1_proto_rawDescData = protoimpl.X.CompressGZIP(file_docs_proto_v1_entity1_proto_rawDescData)
	})
	return file_docs_proto_v1_entity1_proto_rawDescData
}

var file_docs_proto_v1_entity1_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_docs_proto_v1_entity1_proto_goTypes = []interface{}{
	(*CreateEntity1Request)(nil),      // 0: api.proto.v1.CreateEntity1Request
	(*CreateEntity1Response)(nil),     // 1: api.proto.v1.CreateEntity1Response
	(*UpdateEntity1Request)(nil),      // 2: api.proto.v1.UpdateEntity1Request
	(*UpdateEntity1Response)(nil),     // 3: api.proto.v1.UpdateEntity1Response
	(*GetEntity1DetailsRequest)(nil),  // 4: api.proto.v1.GetEntity1DetailsRequest
	(*GetEntity1DetailsResponse)(nil), // 5: api.proto.v1.GetEntity1DetailsResponse
	(*DeleteEntity1Request)(nil),      // 6: api.proto.v1.DeleteEntity1Request
	(*DeleteEntity1Response)(nil),     // 7: api.proto.v1.DeleteEntity1Response
}
var file_docs_proto_v1_entity1_proto_depIdxs = []int32{
	0, // 0: api.proto.v1.Entity1Service.CreateEntity1:input_type -> api.proto.v1.CreateEntity1Request
	2, // 1: api.proto.v1.Entity1Service.UpdateEntity1:input_type -> api.proto.v1.UpdateEntity1Request
	4, // 2: api.proto.v1.Entity1Service.GetEntity1Details:input_type -> api.proto.v1.GetEntity1DetailsRequest
	6, // 3: api.proto.v1.Entity1Service.DeleteEntity1:input_type -> api.proto.v1.DeleteEntity1Request
	1, // 4: api.proto.v1.Entity1Service.CreateEntity1:output_type -> api.proto.v1.CreateEntity1Response
	3, // 5: api.proto.v1.Entity1Service.UpdateEntity1:output_type -> api.proto.v1.UpdateEntity1Response
	5, // 6: api.proto.v1.Entity1Service.GetEntity1Details:output_type -> api.proto.v1.GetEntity1DetailsResponse
	7, // 7: api.proto.v1.Entity1Service.DeleteEntity1:output_type -> api.proto.v1.DeleteEntity1Response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_entity1_proto_init() }
func file_docs_proto_v1_entity1_proto_init() {
	if File_docs_proto_v1_entity1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_docs_proto_v1_entity1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEntity1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_v1_entity1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEntity1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_v1_entity1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEntity1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_v1_entity1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEntity1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_v1_entity1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEntity1DetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_v1_entity1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEntity1DetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_v1_entity1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEntity1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_v1_entity1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEntity1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_docs_proto_v1_entity1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_entity1_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_entity1_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_entity1_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_entity1_proto = out.File
	file_docs_proto_v1_entity1_proto_rawDesc = nil
	file_docs_proto_v1_entity1_proto_goTypes = nil
	file_docs_proto_v1_entity1_proto_depIdxs = nil
}
