env: "local" # dev, prod

http_server:
  port: ":8085"
  read_timeout: 30s
  write_timeout: 30s

postgres:
  dsn: "postgres://user:password123@localhost:5437/dbname?sslmode=disable"
  max_retries: 10
  retry_interval: 5s
  connect_timeout: 30s